<?xml version="1.0" encoding="utf-8"?><Database Name="MedicalMngmt" Class="DatacontextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OHHS4UD\SQLEXPRESS;Initial Catalog=MedicalMngmt;Integrated Security=True" SettingsObjectName="MedicalMngmt.Properties.Settings" SettingsPropertyName="MedicalMngmtConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblPatient" Member="tblPatients">
    <Type Name="tblPatient">
      <Column Name="Registration_No" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mobile_No" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Medicine_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Medicine_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Disease_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Relative_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>